import * as util from '../../src/util';
export interface Transition {
    name?: string,
    cost?: number
}

//should be updated thru LP result.
export const DEFAULT_MARKTYPE_TRANSITIONS = {
    "AREA_BAR": {"name": "AREA_BAR", "cost": 0.4},
    "AREA_LINE": {"name": "AREA_LINE", "cost": 0.2},
    "AREA_POINT": {"name": "AREA_POINT", "cost": 0.5},
    "AREA_TEXT": {"name": "AREA_TEXT", "cost": 1},
    "AREA_TICK": {"name": "AREA_TICK", "cost": 1},
    "BAR_LINE": {"name": "BAR_LINE", "cost": 0.5},
    "BAR_POINT": {"name": "BAR_POINT", "cost": 0.3},
    "BAR_TEXT": {"name": "BAR_TEXT", "cost": 0.7},
    "BAR_TICK": {"name": "BAR_TICK", "cost": 0.7},
    "LINE_POINT": {"name": "LINE_POINT", "cost": 0.4},
    "LINE_TEXT": {"name": "LINE_TEXT", "cost": 0.7},
    "LINE_TICK": {"name": "LINE_TICK", "cost": 0.7},
    "POINT_TEXT": {"name": "POINT_TEXT", "cost": 0.3},
    "POINT_TICK": {"name": "POINT_TICK", "cost": 0.3},
    "TEXT_TICK": {"name": "TEXT_TICK", "cost": 0.3}
};
export const DEFAULT_MARKTYPE_TRANSITION_LIST = [
  "AREA_BAR",
  "AREA_LINE",
  "AREA_POINT",
  "AREA_TEXT",
  "AREA_TICK",
  "BAR_LINE",
  "BAR_POINT",
  "BAR_TEXT",
  "BAR_TICK",
  "LINE_POINT",
  "LINE_TEXT",
  "LINE_TICK",
  "POINT_TEXT",
  "POINT_TICK",
  "TEXT_TICK" ];

export const DEFAULT_TRANSFORM_TRANSITIONS = {
    "SCALE": {"name": "SCALE", "cost": 0.1 },
    "SORT": {"name": "SORT", "cost": 0.2 },
    "BIN": {"name": "BIN", "cost": 0.3 },
    "AGGREGATE": {"name": "AGGREGATE", "cost": 0.4 },
    "FILTER": {"name": "FILTER", "cost": 0.5 },
    "SETTYPE": {"name": "SETTYPE", "cost": 0.6 }
};

export const DEFAULT_TRANSFORM_TRANSITION_LIST = [
  "SCALE",
  "SORT",
  "BIN",
  "AGGREGATE",
  "FILTER",
  "SETTYPE"
];
export const CHANNELS_WITH_TRANSITION_ORDER = [
  "x", "y", "color", "shape", "size", "row", "column", "text"
  // , "detail"
];
export const DEFAULT_ENCODING_TRANSITIONS = {
    "ADD_X": {"name": "ADD_X", "cost": 1 },
    "ADD_Y": {"name": "ADD_Y", "cost": 1 },
    "ADD_COLOR": {"name": "ADD_COLOR", "cost": 1 },
    "ADD_SHAPE": {"name": "ADD_SHAPE", "cost": 1 },
    "ADD_SIZE": {"name": "ADD_SIZE", "cost": 1 },
    "ADD_ROW": {"name": "ADD_ROW", "cost": 1 },
    "ADD_COLUMN": {"name": "ADD_COLUMN", "cost": 1 },
    // "ADD_TEXT": {"name": "ADD_TEXT", "cost": 1 },
    // "ADD_DETAIL": {"name": "ADD_DETAIL", "cost": 1 },

    "ADD_X_COUNT": {"name": "ADD_X_COUNT", "cost": 1 },
    "ADD_Y_COUNT": {"name": "ADD_Y_COUNT", "cost": 1 },
    "ADD_COLOR_COUNT": {"name": "ADD_COLOR_COUNT", "cost": 1 },
    "ADD_SHAPE_COUNT": {"name": "ADD_SHAPE_COUNT", "cost": 1 },
    "ADD_SIZE_COUNT": {"name": "ADD_SIZE_COUNT", "cost": 1 },
    "ADD_ROW_COUNT": {"name": "ADD_ROW_COUNT", "cost": 1 },
    "ADD_COLUMN_COUNT": {"name": "ADD_COLUMN_COUNT", "cost": 1 },
    // "ADD_TEXT_COUNT": {"name": "ADD_TEXT_COUNT", "cost": 1 },
    // "ADD_DETAIL_COUNT": {"name": "ADD_DETAIL_COUNT", "cost": 1 },

    "REMOVE_X_COUNT": {"name": "REMOVE_X_COUNT", "cost": 1 },
    "REMOVE_Y_COUNT": {"name": "REMOVE_Y_COUNT", "cost": 1 },
    "REMOVE_COLOR_COUNT": {"name": "REMOVE_COLOR_COUNT", "cost": 1 },
    "REMOVE_SHAPE_COUNT": {"name": "REMOVE_SHAPE_COUNT", "cost": 1 },
    "REMOVE_SIZE_COUNT": {"name": "REMOVE_SIZE_COUNT", "cost": 1 },
    "REMOVE_ROW_COUNT": {"name": "REMOVE_ROW_COUNT", "cost": 1 },
    "REMOVE_COLUMN_COUNT": {"name": "REMOVE_COLUMN_COUNT", "cost": 1 },
    // "REMOVE_TEXT_COUNT": {"name": "REMOVE_TEXT_COUNT", "cost": 1 },
    // "REMOVE_DETAIL": {"name": "REMOVE_DETAIL", "cost": 1 },

    "REMOVE_X": {"name": "REMOVE_X", "cost": 1 },
    "REMOVE_Y": {"name": "REMOVE_Y", "cost": 1 },
    "REMOVE_COLOR": {"name": "REMOVE_COLOR", "cost": 1 },
    "REMOVE_SHAPE": {"name": "REMOVE_SHAPE", "cost": 1 },
    "REMOVE_SIZE": {"name": "REMOVE_SIZE", "cost": 1 },
    "REMOVE_ROW": {"name": "REMOVE_ROW", "cost": 1 },
    "REMOVE_COLUMN": {"name": "REMOVE_COLUMN", "cost": 1 },
    // "REMOVE_TEXT": {"name": "REMOVE_TEXT", "cost": 1 },
    // "REMOVE_DETAIL": {"name": "REMOVE_DETAIL", "cost": 1 },

    "MODIFY_X": {"name": "MODIFY_X", "cost": 1 },
    "MODIFY_Y": {"name": "MODIFY_Y", "cost": 1 },
    "MODIFY_COLOR": {"name": "MODIFY_COLOR", "cost": 1 },
    "MODIFY_SHAPE": {"name": "MODIFY_SHAPE", "cost": 1 },
    "MODIFY_SIZE": {"name": "MODIFY_SIZE", "cost": 1 },
    "MODIFY_ROW": {"name": "MODIFY_ROW", "cost": 1 },
    "MODIFY_COLUMN": {"name": "MODIFY_COLUMN", "cost": 1 },
    // "MODIFY_TEXT": {"name": "MODIFY_TEXT", "cost": 1 },
    // "MODIFY_DETAIL": {"name": "MODIFY_DETAIL", "cost": 1 },

    "MODIFY_X_ADD_COUNT": {"name": "MODIFY_X_ADD_COUNT", "cost": 1 },
    "MODIFY_Y_ADD_COUNT": {"name": "MODIFY_Y_ADD_COUNT", "cost": 1 },
    "MODIFY_COLOR_ADD_COUNT": {"name": "MODIFY_COLOR_ADD_COUNT", "cost": 1 },
    "MODIFY_SHAPE_ADD_COUNT": {"name": "MODIFY_SHAPE_ADD_COUNT", "cost": 1 },
    "MODIFY_SIZE_ADD_COUNT": {"name": "MODIFY_SIZE_ADD_COUNT", "cost": 1 },
    "MODIFY_ROW_ADD_COUNT": {"name": "MODIFY_ROW_ADD_COUNT", "cost": 1 },
    "MODIFY_COLUMN_ADD_COUNT": {"name": "MODIFY_COLUMN_ADD_COUNT", "cost": 1 },
    // "MODIFY_TEXT_ADD_COUNT": {"name": "MODIFY_TEXT_ADD_COUNT", "cost": 1 },
    // "MODIFY_DETAIL_ADD_COUNT": {"name": "MODIFY_DETAIL_ADD_COUNT", "cost": 1 },

    "MODIFY_X_REMOVE_COUNT": {"name": "MODIFY_X_REMOVE_COUNT", "cost": 1 },
    "MODIFY_Y_REMOVE_COUNT": {"name": "MODIFY_Y_REMOVE_COUNT", "cost": 1 },
    "MODIFY_COLOR_REMOVE_COUNT": {"name": "MODIFY_COLOR_REMOVE_COUNT", "cost": 1 },
    "MODIFY_SHAPE_REMOVE_COUNT": {"name": "MODIFY_SHAPE_REMOVE_COUNT", "cost": 1 },
    "MODIFY_SIZE_REMOVE_COUNT": {"name": "MODIFY_SIZE_REMOVE_COUNT", "cost": 1 },
    "MODIFY_ROW_REMOVE_COUNT": {"name": "MODIFY_ROW_REMOVE_COUNT", "cost": 1 },
    "MODIFY_COLUMN_REMOVE_COUNT": {"name": "MODIFY_COLUMN_REMOVE_COUNT", "cost": 1 },
    // "MODIFY_TEXT_REMOVE_COUNT": {"name": "MODIFY_TEXT_REMOVE_COUNT", "cost": 1 },
    // "MODIFY_DETAIL_REMOVE_COUNT": {"name": "MODIFY_DETAIL_REMOVE_COUNT", "cost": 1 },


    // "MOVE_X_DETAIL": {"name": "MOVE_X_DETAIL", "cost": 1 },
    // "MOVE_X_TEXT": {"name": "MOVE_X_TEXT", "cost": 1 },
    "MOVE_X_COLUMN": {"name": "MOVE_X_COLUMN", "cost": 1 },
    "MOVE_X_ROW": {"name": "MOVE_X_ROW", "cost": 1 },
    "MOVE_X_SIZE": {"name": "MOVE_X_SIZE", "cost": 1 },
    "MOVE_X_SHAPE": {"name": "MOVE_X_SHAPE", "cost": 1 },
    "MOVE_X_COLOR": {"name": "MOVE_X_COLOR", "cost": 1 },
    "MOVE_X_Y": {"name": "MOVE_X_Y", "cost": 1 },

    // "MOVE_Y_DETAIL": {"name": "MOVE_Y_DETAIL", "cost": 1 },
    // "MOVE_Y_TEXT": {"name": "MOVE_Y_TEXT", "cost": 1 },
    "MOVE_Y_COLUMN": {"name": "MOVE_Y_COLUMN", "cost": 1 },
    "MOVE_Y_ROW": {"name": "MOVE_Y_ROW", "cost": 1 },
    "MOVE_Y_SIZE": {"name": "MOVE_Y_SIZE", "cost": 1 },
    "MOVE_Y_SHAPE": {"name": "MOVE_Y_SHAPE", "cost": 1 },
    "MOVE_Y_COLOR": {"name": "MOVE_Y_COLOR", "cost": 1 },
    "MOVE_Y_X": {"name": "MOVE_Y_X", "cost": 1 },

    // "MOVE_COLOR_DETAIL": {"name": "MOVE_COLOR_DETAIL", "cost": 1 },
    // "MOVE_COLOR_TEXT": {"name": "MOVE_COLOR_TEXT", "cost": 1 },
    "MOVE_COLOR_COLUMN": {"name": "MOVE_COLOR_COLUMN", "cost": 1 },
    "MOVE_COLOR_ROW": {"name": "MOVE_COLOR_ROW", "cost": 1 },
    "MOVE_COLOR_SIZE": {"name": "MOVE_COLOR_SIZE", "cost": 1 },
    "MOVE_COLOR_SHAPE": {"name": "MOVE_COLOR_SHAPE", "cost": 1 },
    "MOVE_COLOR_Y": {"name": "MOVE_COLOR_Y", "cost": 1 },
    "MOVE_COLOR_X": {"name": "MOVE_COLOR_X", "cost": 1 },

    // "MOVE_SHAPE_DETAIL": {"name": "MOVE_SHAPE_DETAIL", "cost": 1 },
    // "MOVE_SHAPE_TEXT": {"name": "MOVE_SHAPE_TEXT", "cost": 1 },
    "MOVE_SHAPE_COLUMN": {"name": "MOVE_SHAPE_COLUMN", "cost": 1 },
    "MOVE_SHAPE_ROW": {"name": "MOVE_SHAPE_ROW", "cost": 1 },
    "MOVE_SHAPE_SIZE": {"name": "MOVE_SHAPE_SIZE", "cost": 1 },
    "MOVE_SHAPE_COLOR": {"name": "MOVE_SHAPE_COLOR", "cost": 1 },
    "MOVE_SHAPE_Y": {"name": "MOVE_SHAPE_Y", "cost": 1 },
    "MOVE_SHAPE_X": {"name": "MOVE_SHAPE_X", "cost": 1 },

    // "MOVE_SIZE_DETAIL": {"name": "MOVE_SIZE_DETAIL", "cost": 1 },
    // "MOVE_SIZE_TEXT": {"name": "MOVE_SIZE_TEXT", "cost": 1 },
    "MOVE_SIZE_COLUMN": {"name": "MOVE_SIZE_COLUMN", "cost": 1 },
    "MOVE_SIZE_ROW": {"name": "MOVE_SIZE_ROW", "cost": 1 },
    "MOVE_SIZE_SHAPE": {"name": "MOVE_SIZE_SHAPE", "cost": 1 },
    "MOVE_SIZE_COLOR": {"name": "MOVE_SIZE_COLOR", "cost": 1 },
    "MOVE_SIZE_Y": {"name": "MOVE_SIZE_Y", "cost": 1 },
    "MOVE_SIZE_X": {"name": "MOVE_SIZE_X", "cost": 1 },

    // "MOVE_ROW_DETAIL": {"name": "MOVE_ROW_DETAIL", "cost": 1 },
    // "MOVE_ROW_TEXT": {"name": "MOVE_ROW_TEXT", "cost": 1 },
    "MOVE_ROW_COLUMN": {"name": "MOVE_ROW_COLUMN", "cost": 1 },
    "MOVE_ROW_SIZE": {"name": "MOVE_ROW_SIZE", "cost": 1 },
    "MOVE_ROW_SHAPE": {"name": "MOVE_ROW_SHAPE", "cost": 1 },
    "MOVE_ROW_COLOR": {"name": "MOVE_ROW_COLOR", "cost": 1 },
    "MOVE_ROW_Y": {"name": "MOVE_ROW_Y", "cost": 1 },
    "MOVE_ROW_X": {"name": "MOVE_ROW_X", "cost": 1 },

    // "MOVE_COLUMN_DETAIL": {"name": "MOVE_COLUMN_DETAIL", "cost": 1 },
    // "MOVE_COLUMN_TEXT": {"name": "MOVE_COLUMN_TEXT", "cost": 1 },
    "MOVE_COLUMN_ROW": {"name": "MOVE_COLUMN_ROW", "cost": 1 },
    "MOVE_COLUMN_SIZE": {"name": "MOVE_COLUMN_SIZE", "cost": 1 },
    "MOVE_COLUMN_SHAPE": {"name": "MOVE_COLUMN_SHAPE", "cost": 1 },
    "MOVE_COLUMN_COLOR": {"name": "MOVE_COLUMN_COLOR", "cost": 1 },
    "MOVE_COLUMN_Y": {"name": "MOVE_COLUMN_Y", "cost": 1 },
    "MOVE_COLUMN_X": {"name": "MOVE_COLUMN_X", "cost": 1 },

    // "MOVE_TEXT_DETAIL": {"name": "MOVE_TEXT_DETAIL", "cost": 1 },
    // "MOVE_TEXT_COLUMN": {"name": "MOVE_TEXT_COLUMN", "cost": 1 },
    // "MOVE_TEXT_ROW": {"name": "MOVE_TEXT_ROW", "cost": 1 },
    // "MOVE_TEXT_SIZE": {"name": "MOVE_TEXT_SIZE", "cost": 1 },
    // "MOVE_TEXT_SHAPE": {"name": "MOVE_TEXT_SHAPE", "cost": 1 },
    // "MOVE_TEXT_COLOR": {"name": "MOVE_TEXT_COLOR", "cost": 1 },
    // "MOVE_TEXT_Y": {"name": "MOVE_TEXT_Y", "cost": 1 },
    // "MOVE_TEXT_X": {"name": "MOVE_TEXT_X", "cost": 1 },

    // "MOVE_DETAIL_TEXT": {"name": "MOVE_DETAIL_TEXT", "cost": 1 },
    // "MOVE_DETAIL_COLUMN": {"name": "MOVE_DETAIL_COLUMN", "cost": 1 },
    // "MOVE_DETAIL_ROW": {"name": "MOVE_DETAIL_ROW", "cost": 1 },
    // "MOVE_DETAIL_SIZE": {"name": "MOVE_DETAIL_SIZE", "cost": 1 },
    // "MOVE_DETAIL_SHAPE": {"name": "MOVE_DETAIL_SHAPE", "cost": 1 },
    // "MOVE_DETAIL_COLOR": {"name": "MOVE_DETAIL_COLOR", "cost": 1 },
    // "MOVE_DETAIL_Y": {"name": "MOVE_DETAIL_Y", "cost": 1 },
    // "MOVE_DETAIL_X": {"name": "MOVE_DETAIL_X", "cost": 1 },


    // "SWAP_X_DETAIL": {"name": "SWAP_X_DETAIL", "cost": 1 },
    // "SWAP_X_TEXT": {"name": "SWAP_X_TEXT", "cost": 1 },
    // "SWAP_X_COLUMN": {"name": "SWAP_X_COLUMN", "cost": 1 },
    // "SWAP_X_ROW": {"name": "SWAP_X_ROW", "cost": 1 },
    // "SWAP_X_SIZE": {"name": "SWAP_X_SIZE", "cost": 1 },
    // "SWAP_X_SHAPE": {"name": "SWAP_X_SHAPE", "cost": 1 },
    // "SWAP_X_COLOR": {"name": "SWAP_X_COLOR", "cost": 1 },
    "SWAP_X_Y": {"name": "SWAP_X_Y", "cost": 1 },

    // "SWAP_Y_DETAIL": {"name": "SWAP_Y_DETAIL", "cost": 1 },
    // "SWAP_Y_TEXT": {"name": "SWAP_Y_TEXT", "cost": 1 },
    // "SWAP_Y_COLUMN": {"name": "SWAP_Y_COLUMN", "cost": 1 },
    // "SWAP_Y_ROW": {"name": "SWAP_Y_ROW", "cost": 1 },
    // "SWAP_Y_SIZE": {"name": "SWAP_Y_SIZE", "cost": 1 },
    // "SWAP_Y_SHAPE": {"name": "SWAP_Y_SHAPE", "cost": 1 },
    // "SWAP_Y_COLOR": {"name": "SWAP_Y_COLOR", "cost": 1 },

    // "SWAP_COLOR_DETAIL": {"name": "SWAP_COLOR_DETAIL", "cost": 1 },
    // "SWAP_COLOR_TEXT": {"name": "SWAP_COLOR_TEXT", "cost": 1 },
    // "SWAP_COLOR_COLUMN": {"name": "SWAP_COLOR_COLUMN", "cost": 1 },
    // "SWAP_COLOR_ROW": {"name": "SWAP_COLOR_ROW", "cost": 1 },
    // "SWAP_COLOR_SIZE": {"name": "SWAP_COLOR_SIZE", "cost": 1 },
    // "SWAP_COLOR_SHAPE": {"name": "SWAP_COLOR_SHAPE", "cost": 1 },

    // "SWAP_SHAPE_DETAIL": {"name": "SWAP_SHAPE_DETAIL", "cost": 1 },
    // "SWAP_SHAPE_TEXT": {"name": "SWAP_SHAPE_TEXT", "cost": 1 },
    // "SWAP_SHAPE_COLUMN": {"name": "SWAP_SHAPE_COLUMN", "cost": 1 },
    // "SWAP_SHAPE_ROW": {"name": "SWAP_SHAPE_ROW", "cost": 1 },
    // "SWAP_SHAPE_SIZE": {"name": "SWAP_SHAPE_SIZE", "cost": 1 },

    // "SWAP_SIZE_DETAIL": {"name": "SWAP_SIZE_DETAIL", "cost": 1 },
    // "SWAP_SIZE_TEXT": {"name": "SWAP_SIZE_TEXT", "cost": 1 },
    // "SWAP_SIZE_COLUMN": {"name": "SWAP_SIZE_COLUMN", "cost": 1 },
    // "SWAP_SIZE_ROW": {"name": "SWAP_SIZE_ROW", "cost": 1 },

    // "SWAP_ROW_DETAIL": {"name": "SWAP_ROW_DETAIL", "cost": 1 },
    // "SWAP_ROW_TEXT": {"name": "SWAP_ROW_TEXT", "cost": 1 },
    "SWAP_ROW_COLUMN": {"name": "SWAP_ROW_COLUMN", "cost": 1 },

    // "SWAP_COLUMN_DETAIL": {"name": "SWAP_COLUMN_DETAIL", "cost": 1 },
    // "SWAP_COLUMN_TEXT": {"name": "SWAP_COLUMN_TEXT", "cost": 1 },s

    // "SWAP_TEXT_DETAIL": {"name": "SWAP_TEXT_DETAIL", "cost": 1 },

};

var importedMarktypeTransitions =
{ AREA_BAR: { name: 'AREA_BAR', cost: 0.03 },
  AREA_LINE: { name: 'AREA_LINE', cost: 0.02 },
  AREA_POINT: { name: 'AREA_POINT', cost: 0.04 },
  AREA_TEXT: { name: 'AREA_TEXT', cost: 0.08 },
  AREA_TICK: { name: 'AREA_TICK', cost: 0.04 },
  BAR_LINE: { name: 'BAR_LINE', cost: 0.04 },
  BAR_POINT: { name: 'BAR_POINT', cost: 0.02 },
  BAR_TEXT: { name: 'BAR_TEXT', cost: 0.07 },
  BAR_TICK: { name: 'BAR_TICK', cost: 0.02 },
  LINE_POINT: { name: 'LINE_POINT', cost: 0.03 },
  LINE_TEXT: { name: 'LINE_TEXT', cost: 0.06 },
  LINE_TICK: { name: 'LINE_TICK', cost: 0.03 },
  POINT_TEXT: { name: 'POINT_TEXT', cost: 0.05 },
  POINT_TICK: { name: 'POINT_TICK', cost: 0.01 },
  TEXT_TICK: { name: 'TEXT_TICK', cost: 0.05 } };
var importedTransformTransitions = { SCALE: { name: 'SCALE', cost: 0.6 },
  SORT: { name: 'SORT', cost: 0.61 },
  BIN: { name: 'BIN', cost: 0.62 },
  AGGREGATE: { name: 'AGGREGATE', cost: 0.63 },
  FILTER: { name: 'FILTER', cost: 0.64 },
  SETTYPE: { name: 'SETTYPE', cost: 0.65 } };
var importedEncodingTransitions = { ADD_X: { name: 'ADD_X', cost: 3.97 },
  ADD_Y: { name: 'ADD_Y', cost: 3.97 },
  ADD_COLOR: { name: 'ADD_COLOR', cost: 3.89 },
  ADD_SHAPE: { name: 'ADD_SHAPE', cost: 3.93 },
  ADD_SIZE: { name: 'ADD_SIZE', cost: 3.91 },
  ADD_ROW: { name: 'ADD_ROW', cost: 3.95 },
  ADD_COLUMN: { name: 'ADD_COLUMN', cost: 3.95 },
  ADD_X_COUNT: { name: 'ADD_X_COUNT', cost: 3.96 },
  ADD_Y_COUNT: { name: 'ADD_Y_COUNT', cost: 3.96 },
  ADD_COLOR_COUNT: { name: 'ADD_COLOR_COUNT', cost: 3.88 },
  ADD_SHAPE_COUNT: { name: 'ADD_SHAPE_COUNT', cost: 3.92 },
  ADD_SIZE_COUNT: { name: 'ADD_SIZE_COUNT', cost: 3.9 },
  ADD_ROW_COUNT: { name: 'ADD_ROW_COUNT', cost: 3.94 },
  ADD_COLUMN_COUNT: { name: 'ADD_COLUMN_COUNT', cost: 3.94 },
  REMOVE_X_COUNT: { name: 'REMOVE_X_COUNT', cost: 3.86 },
  REMOVE_Y_COUNT: { name: 'REMOVE_Y_COUNT', cost: 3.86 },
  REMOVE_COLOR_COUNT: { name: 'REMOVE_COLOR_COUNT', cost: 3.82 },
  REMOVE_SHAPE_COUNT: { name: 'REMOVE_SHAPE_COUNT', cost: 3.78 },
  REMOVE_SIZE_COUNT: { name: 'REMOVE_SIZE_COUNT', cost: 3.8 },
  REMOVE_ROW_COUNT: { name: 'REMOVE_ROW_COUNT', cost: 3.84 },
  REMOVE_COLUMN_COUNT: { name: 'REMOVE_COLUMN_COUNT', cost: 3.84 },
  REMOVE_X: { name: 'REMOVE_X', cost: 3.87 },
  REMOVE_Y: { name: 'REMOVE_Y', cost: 3.87 },
  REMOVE_COLOR: { name: 'REMOVE_COLOR', cost: 3.83 },
  REMOVE_SHAPE: { name: 'REMOVE_SHAPE', cost: 3.79 },
  REMOVE_SIZE: { name: 'REMOVE_SIZE', cost: 3.81 },
  REMOVE_ROW: { name: 'REMOVE_ROW', cost: 3.85 },
  REMOVE_COLUMN: { name: 'REMOVE_COLUMN', cost: 3.85 },
  MODIFY_X: { name: 'MODIFY_X', cost: 4.19 },
  MODIFY_Y: { name: 'MODIFY_Y', cost: 4.19 },
  MODIFY_COLOR: { name: 'MODIFY_COLOR', cost: 4.07 },
  MODIFY_SHAPE: { name: 'MODIFY_SHAPE', cost: 4.13 },
  MODIFY_SIZE: { name: 'MODIFY_SIZE', cost: 4.1 },
  MODIFY_ROW: { name: 'MODIFY_ROW', cost: 4.16 },
  MODIFY_COLUMN: { name: 'MODIFY_COLUMN', cost: 4.16 },
  MODIFY_X_ADD_COUNT: { name: 'MODIFY_X_ADD_COUNT', cost: 4.18 },
  MODIFY_Y_ADD_COUNT: { name: 'MODIFY_Y_ADD_COUNT', cost: 4.18 },
  MODIFY_COLOR_ADD_COUNT: { name: 'MODIFY_COLOR_ADD_COUNT', cost: 4.06 },
  MODIFY_SHAPE_ADD_COUNT: { name: 'MODIFY_SHAPE_ADD_COUNT', cost: 4.12 },
  MODIFY_SIZE_ADD_COUNT: { name: 'MODIFY_SIZE_ADD_COUNT', cost: 4.09 },
  MODIFY_ROW_ADD_COUNT: { name: 'MODIFY_ROW_ADD_COUNT', cost: 4.15 },
  MODIFY_COLUMN_ADD_COUNT: { name: 'MODIFY_COLUMN_ADD_COUNT', cost: 4.15 },
  MODIFY_X_REMOVE_COUNT: { name: 'MODIFY_X_REMOVE_COUNT', cost: 4.17 },
  MODIFY_Y_REMOVE_COUNT: { name: 'MODIFY_Y_REMOVE_COUNT', cost: 4.17 },
  MODIFY_COLOR_REMOVE_COUNT: { name: 'MODIFY_COLOR_REMOVE_COUNT', cost: 4.05 },
  MODIFY_SHAPE_REMOVE_COUNT: { name: 'MODIFY_SHAPE_REMOVE_COUNT', cost: 4.11 },
  MODIFY_SIZE_REMOVE_COUNT: { name: 'MODIFY_SIZE_REMOVE_COUNT', cost: 4.08 },
  MODIFY_ROW_REMOVE_COUNT: { name: 'MODIFY_ROW_REMOVE_COUNT', cost: 4.14 },
  MODIFY_COLUMN_REMOVE_COUNT: { name: 'MODIFY_COLUMN_REMOVE_COUNT', cost: 4.14 },
  MOVE_X_COLUMN: { name: 'MOVE_X_COLUMN', cost: 4.04 },
  MOVE_X_ROW: { name: 'MOVE_X_ROW', cost: 3.76 },
  MOVE_X_SIZE: { name: 'MOVE_X_SIZE', cost: 4.01 },
  MOVE_X_SHAPE: { name: 'MOVE_X_SHAPE', cost: 4.02 },
  MOVE_X_COLOR: { name: 'MOVE_X_COLOR', cost: 4 },
  MOVE_X_Y: { name: 'MOVE_X_Y', cost: 4.03 },
  MOVE_Y_COLUMN: { name: 'MOVE_Y_COLUMN', cost: 3.76 },
  MOVE_Y_ROW: { name: 'MOVE_Y_ROW', cost: 4.04 },
  MOVE_Y_SIZE: { name: 'MOVE_Y_SIZE', cost: 4.01 },
  MOVE_Y_SHAPE: { name: 'MOVE_Y_SHAPE', cost: 4.02 },
  MOVE_Y_COLOR: { name: 'MOVE_Y_COLOR', cost: 4 },
  MOVE_Y_X: { name: 'MOVE_Y_X', cost: 4.03 },
  MOVE_COLOR_COLUMN: { name: 'MOVE_COLOR_COLUMN', cost: 3.99 },
  MOVE_COLOR_ROW: { name: 'MOVE_COLOR_ROW', cost: 3.99 },
  MOVE_COLOR_SIZE: { name: 'MOVE_COLOR_SIZE', cost: 3.98 },
  MOVE_COLOR_SHAPE: { name: 'MOVE_COLOR_SHAPE', cost: 3.98 },
  MOVE_COLOR_Y: { name: 'MOVE_COLOR_Y', cost: 4 },
  MOVE_COLOR_X: { name: 'MOVE_COLOR_X', cost: 4 },
  MOVE_SHAPE_COLUMN: { name: 'MOVE_SHAPE_COLUMN', cost: 4.01 },
  MOVE_SHAPE_ROW: { name: 'MOVE_SHAPE_ROW', cost: 4.01 },
  MOVE_SHAPE_SIZE: { name: 'MOVE_SHAPE_SIZE', cost: 3.98 },
  MOVE_SHAPE_COLOR: { name: 'MOVE_SHAPE_COLOR', cost: 3.98 },
  MOVE_SHAPE_Y: { name: 'MOVE_SHAPE_Y', cost: 4.02 },
  MOVE_SHAPE_X: { name: 'MOVE_SHAPE_X', cost: 4.02 },
  MOVE_SIZE_COLUMN: { name: 'MOVE_SIZE_COLUMN', cost: 4 },
  MOVE_SIZE_ROW: { name: 'MOVE_SIZE_ROW', cost: 4 },
  MOVE_SIZE_SHAPE: { name: 'MOVE_SIZE_SHAPE', cost: 3.98 },
  MOVE_SIZE_COLOR: { name: 'MOVE_SIZE_COLOR', cost: 3.98 },
  MOVE_SIZE_Y: { name: 'MOVE_SIZE_Y', cost: 4.01 },
  MOVE_SIZE_X: { name: 'MOVE_SIZE_X', cost: 4.01 },
  MOVE_ROW_COLUMN: { name: 'MOVE_ROW_COLUMN', cost: 4.02 },
  MOVE_ROW_SIZE: { name: 'MOVE_ROW_SIZE', cost: 4 },
  MOVE_ROW_SHAPE: { name: 'MOVE_ROW_SHAPE', cost: 4.01 },
  MOVE_ROW_COLOR: { name: 'MOVE_ROW_COLOR', cost: 3.99 },
  MOVE_ROW_Y: { name: 'MOVE_ROW_Y', cost: 4.04 },
  MOVE_ROW_X: { name: 'MOVE_ROW_X', cost: 3.76 },
  MOVE_COLUMN_ROW: { name: 'MOVE_COLUMN_ROW', cost: 4.02 },
  MOVE_COLUMN_SIZE: { name: 'MOVE_COLUMN_SIZE', cost: 4 },
  MOVE_COLUMN_SHAPE: { name: 'MOVE_COLUMN_SHAPE', cost: 4.01 },
  MOVE_COLUMN_COLOR: { name: 'MOVE_COLUMN_COLOR', cost: 3.99 },
  MOVE_COLUMN_Y: { name: 'MOVE_COLUMN_Y', cost: 3.76 },
  MOVE_COLUMN_X: { name: 'MOVE_COLUMN_X', cost: 4.04 },
  SWAP_X_Y: { name: 'SWAP_X_Y', cost: 3.77 },
  SWAP_ROW_COLUMN: { name: 'SWAP_ROW_COLUMN', cost: 3.76 } };


export const MARKTYPE_TRANSITIONS = importedMarktypeTransitions || DEFAULT_MARKTYPE_TRANSITIONS;
export const TRANSFORM_TRANSITIONS = importedTransformTransitions || DEFAULT_TRANSFORM_TRANSITIONS;
export const ENCODING_TRANSITIONS = importedEncodingTransitions || DEFAULT_ENCODING_TRANSITIONS;
